name: Go Build and Publish

on:
  push:
    branches:
<<<<<<< HEAD
      - goTask
=======
      - main
>>>>>>> 12b6e18e8c7f6e511f84ae131e26f597b3de285c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build Run
      run: go run cmd/commandline/main.go > www/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www
<<<<<<< HEAD
=======
        keep_files: true
>>>>>>> 12b6e18e8c7f6e511f84ae131e26f597b3de285c
